version: "3.8"

services:
  nodejs-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
    environment:
      - DB_HOST=host.docker.internal  # Use host.docker.internal for local MySQL
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=node_db

  mysql-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: node_db
    ports:
      - "3307:3308"  #"3307:3306✅"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
